---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# myTheme

<!-- badges: start -->
<!-- badges: end -->

The goal of myTheme is...providing a consistent professional look for Base R graphics. This package acts as a "style guide" for your R environment. Instead of manually changing colors, fonts, and margins every time you make a plot, this package automates those choices to give your work a consistent, professional "brand." Think of it as the difference between painting a room by hand every time (regular R) versus having a pre-set lighting and color template you can switch on with one button (your package).

Without the package, your plotting code might look like this:

plot(x, y, pch=19, col="#006747", las=1, bty="n", family="sans")

With my package, it becomes two clean steps:

set_my_theme() # Sets the "rules" once
plot(x, y, col = my_colors()[1]) # Just plot the data

## Installation

You can install the development version of **myTheme** from GitHub with:

```r
# install.packages("devtools")
devtools::install_github("Wyanater/myTheme")
```

## Example

Using the package!

library(myTheme)
set_my_theme()
plot(mtcars$wt, mtcars$mpg, col = my_colors()[1], main = "Professional Plot")

How to change the palette to ocean from the default setting of primary.

This pulls the 'ocean' blues instead of the 'primary' greens/golds

plot(mtcars$wt, mtcars$mpg, 
     col = my_colors(palette = "ocean"), 
     pch = 19, 
     main = "Ocean Theme Plot")

To use the second blue in the ocean list

plot(mtcars$wt, mtcars$mpg, 
     col = my_colors("ocean")[2])

# Run this to see the hex codes for ocean
my_colors("ocean")

# Run this to see the default primary codes
my_colors()
